Extension { #name : #Integer }

{ #category : #'*PartialDate-Core' }
Integer >> April [

	^ (PartialDate day: self) April
]

{ #category : #'*PartialDate-Core' }
Integer >> August [

	^ (PartialDate day: self) August
]

{ #category : #'*PartialDate-Core' }
Integer >> December [

	^ (PartialDate day: self) December
]

{ #category : #'*PartialDate-Core' }
Integer >> February [

	^ (PartialDate day: self) February
]

{ #category : #'*PartialDate-Core' }
Integer >> January [

	^ (PartialDate day: self) January
]

{ #category : #'*PartialDate-Core' }
Integer >> July [

	^ (PartialDate day: self) July
]

{ #category : #'*PartialDate-Core' }
Integer >> June [

	^ (PartialDate day: self) June
]

{ #category : #'*PartialDate-Core' }
Integer >> March [

	^ (PartialDate day: self) March
]

{ #category : #'*PartialDate-Core' }
Integer >> May [

	^ (PartialDate day: self) May
]

{ #category : #'*PartialDate-Core' }
Integer >> November [

	^ (PartialDate day: self) November
]

{ #category : #'*PartialDate-Core' }
Integer >> October [

	^ (PartialDate day: self) October
]

{ #category : #'*PartialDate-Core' }
Integer >> September [

	^ (PartialDate day: self) September
]

{ #category : #'*PartialDate-Core' }
Integer >> nd [

	^ PartialDate day: self
]

{ #category : #'*PartialDate-Core' }
Integer >> rd [

	^ PartialDate day: self
]

{ #category : #'*PartialDate-Core' }
Integer >> st [

	^ PartialDate day: self
]

{ #category : #'*PartialDate-Core' }
Integer >> th [

	^ PartialDate day: self
]
